# Generated by Django 3.0.8 on 2020-07-08 09:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NodeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('address_layer', models.IntegerField(choices=[(2, 'L2'), (3, 'L3')])),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifname', models.CharField(max_length=20)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeWirelessNeighbour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_strength', models.IntegerField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.NodeInterface')),
                ('neighbour_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.NodeAddress')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.NodeSnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='NodeRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=60)),
                ('next_hop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.NodeAddress')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.NodeSnapshot')),
            ],
        ),
    ]
