# Generated by Django 6.0.4 on 2026-05-09 01:16
# Manually adjusted: ST_Force3D was removed in PostGIS 3.x; use ST_Force3DZ.
# AlterField generates broken USING clause, so we split state and DB ops.

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_upgrade_pks_to_bigautofield"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE "data_nodesnapshot"
                        ALTER COLUMN "position" TYPE geography(POINTZ, 4326)
                        USING ST_Force3DZ("position"::geometry)::geography;
                    """,
                    reverse_sql="""
                        ALTER TABLE "data_nodesnapshot"
                        ALTER COLUMN "position" TYPE geography(POINT, 4326)
                        USING ST_GeomFromWKB(ST_AsBinary("position"::geometry), 4326)::geography;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="nodesnapshot",
                    name="position",
                    field=django.contrib.gis.db.models.fields.PointField(
                        dim=3, geography=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
