# Generated by Django 6.0.4 on 2026-05-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_snapshot_position_3d"),
    ]

    operations = [
        migrations.CreateModel(
            name="Radio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "radio_type",
                    models.CharField(
                        choices=[
                            ("wifi", "WiFi"),
                            ("lora", "LoRa"),
                            ("cellular", "Cellular"),
                            ("bluetooth", "Bluetooth"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bands",
                    models.JSONField(
                        default=list,
                        help_text='Supported band/frequency identifiers, e.g. ["2.4GHz", "5GHz"]',
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radios",
                        to="data.node",
                    ),
                ),
            ],
        ),
    ]
