# Generated by Django 6.0.4 on 2026-05-09 01:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_restructure_snapshot_remove_wirelessneighbour"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        dim=3, geography=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="nodesnapshot",
            name="captured_at",
            field=models.DateTimeField(help_text="Device-reported capture timestamp"),
        ),
        migrations.CreateModel(
            name="RadioReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        help_text='Frequency band identifier, e.g. "2.4GHz"',
                        max_length=20,
                    ),
                ),
                (
                    "rssi_dbm",
                    models.IntegerField(help_text="Received signal strength in dBm"),
                ),
                (
                    "snr_db",
                    models.FloatField(
                        blank=True, help_text="Signal-to-noise ratio in dB", null=True
                    ),
                ),
                (
                    "ground_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="readings",
                        to="data.groundstation",
                    ),
                ),
                (
                    "radio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="data.radio",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radio_readings",
                        to="data.nodesnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["snapshot", "radio", "band"],
                        name="data_radior_snapsho_f59103_idx",
                    )
                ],
            },
        ),
    ]
