# Generated by Django 6.0.4 on 2026-05-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_add_groundstation_radioreading"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="radio",
            constraint=models.UniqueConstraint(
                fields=("node", "radio_type"), name="uniq_radio_node_radio_type"
            ),
        ),
    ]
