# Generated by Django 6.0.4 on 2026-05-09 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_radio_unique_constraint_and_bands_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="radioreading",
            name="relay_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node acting as receiver: relay UAV extending coverage, or search node temporarily filling a gap",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relay_readings",
                to="data.node",
            ),
        ),
        migrations.AddConstraint(
            model_name="radioreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ground_station__isnull", False),
                    ("relay_node__isnull", False),
                    _negated=True,
                ),
                name="radioreading_single_receiver",
            ),
        ),
    ]
