# Generated by Django 6.0.4 on 2026-05-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_radioreading_add_relay_node"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="radioreading",
            name="radioreading_single_receiver",
        ),
        migrations.AlterField(
            model_name="groundstation",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="radioreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ground_station__isnull", False), ("relay_node__isnull", True)
                    ),
                    models.Q(
                        ("ground_station__isnull", True), ("relay_node__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="radioreading_exactly_one_receiver",
            ),
        ),
    ]
