# Generated by Django 6.0.5 on 2026-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_groundstation_name_unique_xor_receiver_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nodesnapshot',
            index=models.Index(fields=['captured_at'], name='data_nodesn_capture_ad394c_idx'),
        ),
        migrations.AddIndex(
            model_name='nodesnapshot',
            index=models.Index(fields=['received_at'], name='data_nodesn_receive_bb9f42_idx'),
        ),
    ]
