# Generated by Django 6.0.5 on 2026-05-19 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area_of_operation_notes', models.TextField(blank=True)),
                ('ground_station_layout', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='data.mission')),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
    ]
