# Generated by Django 6.0.5 on 2026-05-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_mission_phase'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='missionphase',
            index=models.Index(fields=['mission', 'started_at', 'ended_at'], name='data_missio_mission_7b2703_idx'),
        ),
        migrations.AddConstraint(
            model_name='missionphase',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', False), _connector='OR'), name='missionphase_ended_requires_started'),
        ),
        migrations.AddConstraint(
            model_name='missionphase',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__lte', models.F('ended_at')), _connector='OR'), name='missionphase_started_at_lte_ended_at'),
        ),
    ]
