# Generated by Django 6.1 on 2026-08-29 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_missionphase_data_missio_mission_7b2703_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('zoom', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)])),
            ],
            options={
                'verbose_name': 'map defaults',
                'verbose_name_plural': 'map defaults',
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='map_latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='mission',
            name='map_longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddField(
            model_name='mission',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)]),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('map_latitude__isnull', True), ('map_longitude__isnull', True)), models.Q(('map_latitude__isnull', False), ('map_longitude__isnull', False)), _connector='OR'), name='mission_map_centre_both_or_neither'),
        ),
    ]
